import 'dotenv/config'; import { connectDB } from './db.js';
const ideas=[
['AI Study Coach','An adaptive study planner that turns a syllabus into daily revision tasks.','AI','https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=900&q=70','Secondary and university students','Students often revise without a realistic plan and struggle to identify weak areas.','Use AI-assisted planning, short quizzes and progress signals to adapt a weekly study route.'],
['Clinic Queue Lite','A lightweight queue and appointment visibility tool for small clinics.','Health','https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=900&q=70','Small clinics and patients','Patients lose time because they cannot estimate waiting time before arriving.','Give clinics a simple web dashboard and patients a live queue estimate with privacy-safe ticket numbers.'],
['SkillSwap Campus','A campus marketplace where students exchange short peer-learning sessions.','Education','https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=900&q=70','College and university students','Students need practical help but tutoring can be expensive or hard to schedule.','Match students who can teach complementary skills and use reputation feedback to build trust.'],
['Refill Route','A map-first directory for refill and low-waste shopping points.','Environment','https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=900&q=70','Eco-conscious urban shoppers','People want to reduce packaging waste but do not know where refill options exist nearby.','Crowdsource verified refill locations, accepted container types and recent availability updates.'],
['MicroBiz Ledger','A simple cash-flow dashboard for very small businesses.','Finance','https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=900&q=70','Micro and small business owners','Owners often mix personal and business cash and lose visibility into weekly profit.','Provide simple income/expense capture, cash runway views and plain-language weekly summaries.'],
['LocalCart Collective','A shared online storefront for neighborhood home-based sellers.','E-commerce','https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=900&q=70','Home-based sellers and local buyers','Small sellers struggle to maintain individual storefronts and attract repeat local customers.','Create one neighborhood marketplace with seller profiles, pickup zones and combined discovery.'],
['Farm Alert Vision','Phone-camera crop issue reporting with expert escalation.','Tech','https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=900&q=70','Smallholder farmers','Crop symptoms are noticed early but farmers may not know how to describe them or who to ask.','Guide users through photo capture, symptom questions and escalation to verified agriculture advisers.'],
['Volunteer Match Board','A verified local board matching short volunteer tasks with nearby helpers.','Social Impact','https://images.unsplash.com/photo-1559027615-cd4628902d4a?auto=format&fit=crop&w=900&q=70','Community groups and volunteers','Small community groups need short-term help but lack a reliable way to reach volunteers.','Publish time-bounded tasks, verify organizers and track simple completion feedback.'],
['Focus Room Booking','A shared quiet-space availability board for schools and coworking hubs.','Other','https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=70','Students and coworking members','People waste time searching for an available quiet place for calls or concentrated work.','Let participating spaces publish live availability and simple usage rules in one directory.']
];
const db=await connectDB();await db.collection('ideas').deleteMany({seeded:true});await db.collection('ideas').insertMany(ideas.map((x,i)=>({title:x[0],shortDescription:x[1],detailedDescription:`${x[1]} The concept focuses on a small, testable first version so community feedback can validate demand before the team expands features.`,category:x[2],imageURL:x[3],targetAudience:x[4],problemStatement:x[5],proposedSolution:x[6],tags:[x[2].toLowerCase(),'startup','validation'],estimatedBudget:i%2?'BDT 3–5 lakh':'BDT 5–8 lakh',creatorEmail:'demo@ideavault.example',creatorName:'IdeaVault Demo',creatorPhoto:'',likes:[],seeded:true,createdAt:new Date(Date.now()-i*86400000),updatedAt:new Date()})));console.log('Seeded 9 ideas');process.exit(0);
