import 'dotenv/config';
import express from 'express'; import cors from 'cors'; import jwt from 'jsonwebtoken'; import { ObjectId } from 'mongodb'; import { connectDB } from './db.js'; import { requireJwt,requireSameEmail } from './auth.js'; import { cleanIdea,escapeRegex,oid } from './helpers.js'; import { verifyFirebaseToken } from './firebaseAdmin.js';
if(!process.env.JWT_SECRET) console.warn('WARNING: JWT_SECRET is missing. Add it before using authenticated routes.');
const app=express();const allowed=(process.env.CLIENT_ORIGIN||'http://localhost:3000').split(',').map(x=>x.trim());app.use(cors({origin:(origin,cb)=>!origin||allowed.includes(origin)?cb(null,true):cb(new Error('Origin not allowed')),credentials:true}));app.use(express.json({limit:'1mb'}));
app.get('/health',(req,res)=>res.json({ok:true,service:'IdeaVault API'}));
app.post('/jwt',async(req,res)=>{try{if(!process.env.JWT_SECRET)return res.status(503).json({message:'JWT secret not configured'});const {firebaseToken}=req.body;if(!firebaseToken)return res.status(400).json({message:'firebaseToken is required'});const decoded=await verifyFirebaseToken(firebaseToken);const token=jwt.sign({email:decoded.email,uid:decoded.uid},process.env.JWT_SECRET,{expiresIn:'7d'});res.json({token})}catch(e){res.status(401).json({message:e.message})}});

app.post('/users',requireJwt,async(req,res)=>{try{const {email,name,photoURL}=req.body;if(email!==req.auth.email)return res.status(403).json({message:'Forbidden'});const db=await connectDB();await db.collection('users').updateOne({email},{$set:{name:name||'IdeaVault User',photoURL:photoURL||'',updatedAt:new Date()},$setOnInsert:{createdAt:new Date()}},{upsert:true});res.json({ok:true})}catch(e){res.status(500).json({message:e.message})}});
app.patch('/users/:email',requireJwt,requireSameEmail,async(req,res)=>{try{const db=await connectDB();await db.collection('users').updateOne({email:req.params.email},{$set:{name:String(req.body.name||'').trim(),photoURL:String(req.body.photoURL||'').trim(),updatedAt:new Date()}});res.json({ok:true})}catch(e){res.status(500).json({message:e.message})}});

app.get('/ideas/trending',async(req,res)=>{try{const db=await connectDB();const limit=Math.min(Math.max(parseInt(req.query.limit||'6',10)||6,1),20);const rows=await db.collection('ideas').aggregate([
 {$lookup:{from:'comments',localField:'_id',foreignField:'ideaId',as:'commentDocs'}},
 {$addFields:{likeCount:{$size:{$ifNull:['$likes',[]]}},commentCount:{$size:'$commentDocs'}}},
 {$addFields:{trendScore:{$add:[{$multiply:['$likeCount',3]},{$multiply:['$commentCount',2]}]}}},
 {$sort:{trendScore:-1,createdAt:-1}},{$limit:limit},{$project:{commentDocs:0}}
]).toArray();res.json(rows)}catch(e){res.status(500).json({message:e.message})}});
app.get('/ideas',async(req,res)=>{try{const db=await connectDB();const filter={};if(req.query.search)filter.title={$regex:escapeRegex(String(req.query.search)),$options:'i'};if(req.query.category&&req.query.category!=='All')filter.category=String(req.query.category);if(req.query.from||req.query.to){filter.createdAt={};if(req.query.from)filter.createdAt.$gte=new Date(`${req.query.from}T00:00:00.000Z`);if(req.query.to)filter.createdAt.$lte=new Date(`${req.query.to}T23:59:59.999Z`)}const limit=req.query.limit?Math.min(parseInt(req.query.limit,10)||100,100):100;const rows=await db.collection('ideas').aggregate([{$match:filter},{$sort:{createdAt:-1}},{$limit:limit},{$lookup:{from:'comments',localField:'_id',foreignField:'ideaId',as:'commentDocs'}},{$addFields:{likeCount:{$size:{$ifNull:['$likes',[]]}},commentCount:{$size:'$commentDocs'}}},{$project:{commentDocs:0}}]).toArray();res.json(rows)}catch(e){res.status(500).json({message:e.message})}});
app.get('/ideas/user/:email',requireJwt,requireSameEmail,async(req,res)=>{try{const db=await connectDB();res.json(await db.collection('ideas').find({creatorEmail:req.params.email}).sort({createdAt:-1}).toArray())}catch(e){res.status(500).json({message:e.message})}});
app.post('/ideas',requireJwt,async(req,res)=>{try{const idea=cleanIdea(req.body);if(req.body.creatorEmail!==req.auth.email)return res.status(403).json({message:'Creator email mismatch'});const db=await connectDB();const doc={...idea,creatorEmail:req.auth.email,creatorName:String(req.body.creatorName||'IdeaVault User'),creatorPhoto:String(req.body.creatorPhoto||''),likes:[],createdAt:new Date(),updatedAt:new Date()};const r=await db.collection('ideas').insertOne(doc);res.status(201).json({insertedId:r.insertedId})}catch(e){res.status(400).json({message:e.message})}});
app.get('/ideas/:id',requireJwt,async(req,res)=>{try{const _id=oid(req.params.id);if(!_id)return res.status(400).json({message:'Invalid idea id'});const db=await connectDB();const idea=await db.collection('ideas').findOne({_id});if(!idea)return res.status(404).json({message:'Idea not found'});res.json(idea)}catch(e){res.status(500).json({message:e.message})}});
app.patch('/ideas/:id',requireJwt,async(req,res)=>{try{const _id=oid(req.params.id);if(!_id)return res.status(400).json({message:'Invalid idea id'});const db=await connectDB();const old=await db.collection('ideas').findOne({_id});if(!old)return res.status(404).json({message:'Idea not found'});if(old.creatorEmail!==req.auth.email)return res.status(403).json({message:'Only the creator can update this idea'});const update=cleanIdea(req.body);await db.collection('ideas').updateOne({_id},{$set:{...update,updatedAt:new Date()}});res.json({ok:true})}catch(e){res.status(400).json({message:e.message})}});
app.delete('/ideas/:id',requireJwt,async(req,res)=>{try{const _id=oid(req.params.id);if(!_id)return res.status(400).json({message:'Invalid idea id'});const db=await connectDB();const old=await db.collection('ideas').findOne({_id});if(!old)return res.status(404).json({message:'Idea not found'});if(old.creatorEmail!==req.auth.email)return res.status(403).json({message:'Only the creator can delete this idea'});await Promise.all([db.collection('ideas').deleteOne({_id}),db.collection('comments').deleteMany({ideaId:_id}),db.collection('bookmarks').deleteMany({ideaId:_id})]);res.json({ok:true})}catch(e){res.status(500).json({message:e.message})}});
app.post('/ideas/:id/like',requireJwt,async(req,res)=>{try{const _id=oid(req.params.id);if(!_id)return res.status(400).json({message:'Invalid idea id'});const db=await connectDB();const idea=await db.collection('ideas').findOne({_id});if(!idea)return res.status(404).json({message:'Idea not found'});const likes=idea.likes||[];const liked=!likes.includes(req.auth.email);await db.collection('ideas').updateOne({_id},liked?{$addToSet:{likes:req.auth.email}}:{$pull:{likes:req.auth.email}});const fresh=await db.collection('ideas').findOne({_id},{projection:{likes:1}});res.json({liked,likes:fresh.likes||[]})}catch(e){res.status(500).json({message:e.message})}});

app.get('/comments/idea/:ideaId',requireJwt,async(req,res)=>{try{const ideaId=oid(req.params.ideaId);if(!ideaId)return res.status(400).json({message:'Invalid idea id'});const db=await connectDB();res.json(await db.collection('comments').find({ideaId}).sort({createdAt:-1}).toArray())}catch(e){res.status(500).json({message:e.message})}});
app.post('/comments',requireJwt,async(req,res)=>{try{const ideaId=oid(req.body.ideaId);const text=String(req.body.text||'').trim();if(!ideaId||!text)return res.status(400).json({message:'ideaId and comment text are required'});const db=await connectDB();const idea=await db.collection('ideas').findOne({_id:ideaId});if(!idea)return res.status(404).json({message:'Idea not found'});const user=await db.collection('users').findOne({email:req.auth.email});const doc={ideaId,userEmail:req.auth.email,userName:user?.name||'IdeaVault User',text,createdAt:new Date(),updatedAt:new Date()};const r=await db.collection('comments').insertOne(doc);res.status(201).json({insertedId:r.insertedId})}catch(e){res.status(500).json({message:e.message})}});
app.patch('/comments/:id',requireJwt,async(req,res)=>{try{const _id=oid(req.params.id);const text=String(req.body.text||'').trim();if(!_id||!text)return res.status(400).json({message:'Valid comment id and text are required'});const db=await connectDB();const c=await db.collection('comments').findOne({_id});if(!c)return res.status(404).json({message:'Comment not found'});if(c.userEmail!==req.auth.email)return res.status(403).json({message:'You can edit only your own comment'});await db.collection('comments').updateOne({_id},{$set:{text,updatedAt:new Date()}});res.json({ok:true})}catch(e){res.status(500).json({message:e.message})}});
app.delete('/comments/:id',requireJwt,async(req,res)=>{try{const _id=oid(req.params.id);if(!_id)return res.status(400).json({message:'Invalid comment id'});const db=await connectDB();const c=await db.collection('comments').findOne({_id});if(!c)return res.status(404).json({message:'Comment not found'});if(c.userEmail!==req.auth.email)return res.status(403).json({message:'You can delete only your own comment'});await db.collection('comments').deleteOne({_id});res.json({ok:true})}catch(e){res.status(500).json({message:e.message})}});
app.get('/interactions/:email',requireJwt,requireSameEmail,async(req,res)=>{try{const db=await connectDB();const rows=await db.collection('comments').aggregate([{$match:{userEmail:req.params.email}},{$sort:{createdAt:-1}},{$lookup:{from:'ideas',localField:'ideaId',foreignField:'_id',as:'idea'}},{$unwind:{path:'$idea',preserveNullAndEmptyArrays:true}}]).toArray();res.json(rows)}catch(e){res.status(500).json({message:e.message})}});

app.post('/bookmarks/:ideaId',requireJwt,async(req,res)=>{try{const ideaId=oid(req.params.ideaId);if(!ideaId)return res.status(400).json({message:'Invalid idea id'});const db=await connectDB();const filter={userEmail:req.auth.email,ideaId};const exists=await db.collection('bookmarks').findOne(filter);if(exists){await db.collection('bookmarks').deleteOne(filter);return res.json({bookmarked:false})}await db.collection('bookmarks').insertOne({...filter,createdAt:new Date()});res.json({bookmarked:true})}catch(e){res.status(500).json({message:e.message})}});
app.get('/bookmarks/:email',requireJwt,requireSameEmail,async(req,res)=>{try{const db=await connectDB();const rows=await db.collection('bookmarks').aggregate([{$match:{userEmail:req.params.email}},{$sort:{createdAt:-1}},{$lookup:{from:'ideas',localField:'ideaId',foreignField:'_id',as:'idea'}},{$unwind:'$idea'},{$replaceRoot:{newRoot:'$idea'}}]).toArray();res.json(rows)}catch(e){res.status(500).json({message:e.message})}});

app.use((req,res)=>res.status(404).json({message:'API route not found'}));
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({message:err.message||'Server error'})});
const port=process.env.PORT||5000;app.listen(port,()=>console.log(`IdeaVault API running on port ${port}`));
